package br.com.pempec.finance.utils;

public interface ConstanteSeguranca {

    //PARAMETROS
    final String TELA_SACADO = "SACADO";
    final String TELA_CEDENTE = "CEDENTE";
    final String TELA_ORGANIZACAO = "ORGANIZACAO";
    final String TELA_FUNCIONARIO = "FUNCIONARIO";
    final String TELA_BANCO = "BANCO";
    final String TELA_CONTA_BANCARIA = "CONTABANCARIA";
    final String TELA_CIDADE = "CIDADE";
    final String TELA_BAIRRO = "BAIRRO";
    final String TELA_FORMA_PAGAMENTO = "FORMAPAGAMENTO";
    final String TELA_LOCAL_PAGAMENTO = "LOCALPAGAMENTO";
    final String TELA_HISTORICO = "HISTORICO";
    final String TELA_CENTRO_CUSTOS = "CENTROCUSTOS";
    final String TELA_TIPO_SACADO = "TIPOSACADO";
    final String TELA_TIPO_CEDENTE = "TIPOCEDENTE";
    final String TELA_TIPO_OPERACAO_BANCARIA = "TIPOOPERACAOBANCARIA";
    final String TELA_TIPO_STATUS = "TIPOSTATUS";
    final String TELA_TIPO_ACRESCIMO = "TIPOACRESCIMO";
    final String TELA_TIPO_DEDUCAO = "TIPODEDUCAO";
    final String TELA_TIPO_COBRANCA = "TIPOCOBRANCA";
    //SEGURANCA
    final String TELA_USUARIO = "USUARIO";
    final String TELA_GRUPO = "GRUPO";
    //CONTAS A PAGAR
    final String TELA_CADASTRAR_CONTAS_PAGAR = "CONTASPAGAR";
    final String TELA_BAIXAR_CONTAS_PAGAR = "BAIXARCONTASPAGAR";
    final String TELA_PARTICIONAR_CONTAS_PAGAR = "PARTICIONARCONTASPAGAR";
    final String TELA_CANCELAR_BAIXA_CONTAS_PAGAR = "CANCELARBAIXACONTASPAGAR";
    final String TELA_RECIBO_CONTAS_PAGAR = "RECIBOCONTASPAGAR";
    //CONTAS A RECEBER
    final String TELA_CADASTRAR_CONTAS_RECEBER = "CONTASRECEBER";
    final String TELA_BAIXAR_CONTAS_RECEBER = "BAIXARCONTASRECEBER";
    final String TELA_PARTICIONAR_CONTAS_RECEBER = "PARTICIONARCONTASRECEBER";
    final String TELA_CANCELAR_BAIXA_CONTAS_RECEBER = "CANCELARBAIXACONTASRECEBER";
    final String TELA_RECIBO_CONTAS_RECEBER = "RECIBOCONTASRECEBER";
    //CONCILIACAO BANCARIA
    final String TELA_TRANSFERENCIA = "TRANSFERENCIA";
    final String TELA_GERAR_CHEQUES = "GERARCHEQUES";
    final String TELA_COMPENSAR_CHEQUES = "COMPENSARCHEQUES";
    final String TELA_ESTORNAR_CHEQUE_COMPENSADO = "ESTORNACHEQUECOMPENSADO";
    final String TELA_COPIA_CHEQUE = "COPIACHEQUE";
    final String TELA_CONCILIACAO_ABA_CREDITO = "CONCILIACAOABACREDITOS";
    final String TELA_CONCILIACAO_ABA_DEBITO = "CONCILIACAOABADEBITOS";
    //TESOURARIA    
    final String TELA_TESOURARIA_ABA_CREDITO = "TESOURARIAABACREDITOS";
    final String TELA_TESOURARIA_ABA_DEBITO = "TESOURARIAABADEBITOS";
    final String TELA_TESOURARIA_RECIBO_DESPESA = "TESOURARIARECIBODESPESA";
    final String TELA_TESOURARIA_RECIBO_RECEITA = "TESOURARIARECIBORECEITA";
    //RELATORIO
    final String TELA_RELATORIO_CONTA_PAGAR = "RELATORIOCONTASPAGAR";
    final String TELA_RELATORIO_CONTA_RECEBER = "RELATORIOCONTASRECEBER";
    final String TELA_RELATORIO_FLUXO_CAIXA = "RELATORIOFLUXOCAIXA";
    final String TELA_RELATORIO_EXTRATRO_BANCARIO = "RELATORIOEXTRATOBANCARIO";
    final String TELA_RELATORIO_DMS = "RELATORIODMS";
}
